### ISSUE TITLE
[BUG] Cannot register Yubikey 5C

### ISSUE THREAD

**Issue by derritter88** [michib/nextcloud_twofactor_webauthn#37] opened 2020-04-18 07:16 UTC
I have installed the new Webauthn 2FA to test it (currently I am using U2F/TOTP).

As soon as I would like to register my Yubikey I will get an excpetion which can be found at the log:

`

  | RuntimeException: The Metadata Statement for the AAGUID "ee882879-721c-4913-9775-3dfcce97072a" is missing/var/www/cloud/apps/twofactor_webauthn/vendor/web-auth/webauthn-lib/src/AuthenticatorAttestationResponseValidator.php - line 148: Webauthn\AuthenticatorAttestationResponseValidator->checkMetadataStatement(Webauthn\Att ... {})/var/www/cloud/apps/twofactor_webauthn/lib/Service/WebauthnManager.php - line 245: Webauthn\AuthenticatorAttestationResponseValidator->check(Webauthn\Aut ... {}, Webauthn\Pub ... {}, Slim\Http\Request {})/var/www/cloud/apps/twofactor_webauthn/lib/Controller/SettingsController.php - line 87: OCA\TwoFactorWebauthn\Service\WebauthnManager->finishRegister(OC\User\User {}, "Yubikey 5C", "{\"id\":\"n ... }")/var/www/cloud/lib/private/AppFramework/Http/Dispatcher.php - line 170: OCA\TwoFactorWebauthn\Controller\SettingsController->finishRegister("Yubikey 5C", "{\"id\":\"n ... }")/var/www/cloud/lib/private/AppFramework/Http/Dispatcher.php - line 99: OC\AppFramework\Http\Dispatcher->executeController(OCA\TwoFacto ... {}, "finishRegister")/var/www/cloud/lib/private/AppFramework/App.php - line 125: OC\AppFramework\Http\Dispatcher->dispatch(OCA\TwoFacto ... {}, "finishRegister")/var/www/cloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("OCA\\TwoFac ... r", "finishRegister", OC\AppFramew ... {}, { _route: "t ... "})<<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "t ... "})/var/www/cloud/lib/private/Route/Router.php - line 299: call_user_func(OC\AppFramew ... {}, { _route: "t ... "})/var/www/cloud/lib/base.php - line 1008: OC\Route\Router->match("/apps/twofa ... r")/var/www/cloud/index.php - line 38: OC::handleRequest()
-- | --

`

**Comment by derritter88** [comment] 2020-04-18 07:18
Okay now in a better, more readable format:


	RuntimeException: The Metadata Statement for the AAGUID "ee882879-721c-4913-9775-3dfcce97072a" is missing

    /var/www/cloud/apps/twofactor_webauthn/vendor/web-auth/webauthn-lib/src/AuthenticatorAttestationResponseValidator.php - line 148:

    Webauthn\AuthenticatorAttestationResponseValidator->checkMetadataStatement(Webauthn\Att ... {})

    /var/www/cloud/apps/twofactor_webauthn/lib/Service/WebauthnManager.php - line 245:

    Webauthn\AuthenticatorAttestationResponseValidator->check(Webauthn\Aut ... {}, Webauthn\Pub ... {}, Slim\Http\Request {})

    /var/www/cloud/apps/twofactor_webauthn/lib/Controller/SettingsController.php - line 87:

    OCA\TwoFactorWebauthn\Service\WebauthnManager->finishRegister(OC\User\User {}, "Yubikey 5C", "{\"id\":\"n ... }")

    /var/www/cloud/lib/private/AppFramework/Http/Dispatcher.php - line 170:

    OCA\TwoFactorWebauthn\Controller\SettingsController->finishRegister("Yubikey 5C", "{\"id\":\"n ... }")

    /var/www/cloud/lib/private/AppFramework/Http/Dispatcher.php - line 99:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\TwoFacto ... {}, "finishRegister")

    /var/www/cloud/lib/private/AppFramework/App.php - line 125:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\TwoFacto ... {}, "finishRegister")

    /var/www/cloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("OCA\\TwoFac ... r", "finishRegister", OC\AppFramew ... {}, { _route: "t ... "})

    <<closure>>

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "t ... "})

    /var/www/cloud/lib/private/Route/Router.php - line 299:

    call_user_func(OC\AppFramew ... {}, { _route: "t ... "})

    /var/www/cloud/lib/base.php - line 1008:

    OC\Route\Router->match("/apps/twofa ... r")

    /var/www/cloud/index.php - line 38:

    OC::handleRequest()

**Comment by michib** [comment] 2020-04-20 17:02
Hi, thanks for your feedback. But unfortunately you didn't provide the needed information asked by the bug issue template. Would be great, if you could provide this information.
And i think i'm going to need the response data and the table row of the used key. Would be great if you could send these information to me.
Afterwards i can start to investigate this issue.

**Comment by derritter88** [comment] 2020-04-20 18:31
Sorry - I just clicked on issues and created a new one.
The bug report is below:

Describe the bug A clear and concise description of what the bug is.

To Reproduce Steps to reproduce the behavior:

1. Login to Nextcloud with existing 2FA (U2F or TOTP)
2. Click on your user icon and go to settings
3. Go to security
4. Scroll to "Webauthn Devices" and click on the "Add Webauthn device"
5. Enter your unlock pin (Windows 10 setting)
6. Push the Yubikey button
7. Enter a name for the device at Nextcloud
8. Click "Add"
9. Stucks at " Adding your device … " while circle is rotating

Expected behavior A clear and concise description of what you expected to happen.
Yubikey will be added and is registered at Nextcloud to use as 2FA.

Screenshots If applicable, add screenshots to help explain your problem.
![Unbenannt](https://user-images.githubusercontent.com/8606313/79786239-68a75400-8345-11ea-8b83-8a19f23e4103.PNG)

Environment (feel free to add relevant information)

    Twofactor_Webauthn Version: 0.2.4
    Nextcloud Version: 18.0.3
    PHP Version: 7.3 (FPM)
    Database with Version: Postgresql 10
    Browser with Version: Firefox 75

Webauthn Devices Please list here your webauthn devices, which relate to the issue, eg:
    Yubikey 5 C


Nextcloud error log Please attach the nextcloud error log, if applicable
see above


Browser error log Please attach the error from the developer console of the browser, if applicable
`
Error persisting webauthn registration Error: "Request failed with status code 500"
    exports createError.js:16
    exports settle.js:17
    onreadystatechange xhr.js:61
AddDeviceDialog.vue:189
    saveRegistrationData AddDeviceDialog.vue:189
Error: "Server error while trying to complete webauthn device registration"
    saveRegistrationData AddDeviceDialog.vue:190
`

Additional context Add any other context about the problem here.

**Comment by derritter88** [comment] 2020-04-20 18:33
Regarding 

> And i think i'm going to need the response data and the table row of the used key. Would be great if you could send these information to me.

How do I get those data?

**Comment by michib** [comment] 2020-04-27 18:08
Hi, sorry for the delay on my answer, but the weather was just to fine to be on my computer on my spare time ;-)
But to get the response with firefox, you have to open the "Developer Tools" with F12. There is a tab "Network". Open it and type webauthn in the filter bar. This makes it easier to find the request. The important request is "finishregister". I think i will need the "Request Payload" on the tab "Params", to investigate this issue.
![image](https://user-images.githubusercontent.com/5346721/80405246-a61a5d00-88c2-11ea-9a16-95011735bda2.png)

**Comment by derritter88** [comment] 2020-04-27 18:34
I see - same here, been riding my bike the last couple of days :-)
Regarding the data.
I have checked with Firefox and I get a 500 Internal Server Error with a POST.
The requested data would be:
`{"name":"Yubikey 5C","data":"{\"id\":\"dz48uhxSJMINtgwizu9vvPf5o13MLrGQhwk1EDxsLRUCOIKYg03yCFzAtvhLLhrKomS7wqKXwiXl3Zb3P_UEew\",\"type\":\"public-key\",\"rawId\":\"dz48uhxSJMINtgwizu9vvPf5o13MLrGQhwk1EDxsLRUCOIKYg03yCFzAtvhLLhrKomS7wqKXwiXl3Zb3P/UEew==\",\"response\":{\"clientDataJSON\":\"eyJjaGFsbGVuZ2UiOiJ3S2RtVURqUGtXS3JHRS1objlFbG84aGVkVjNUd0NXTDJvWE8xUElOZU53IiwiY2xpZW50RXh0ZW5zaW9ucyI6e30sImhhc2hBbGdvcml0aG0iOiJTSEEtMjU2Iiwib3JpZ2luIjoiaHR0cHM6Ly9jbG91ZC5oa3MtcHJvamVrdC5hdCIsInR5cGUiOiJ3ZWJhdXRobi5jcmVhdGUifQ==\",\"attestationObject\":\"o2NmbXRmcGFja2VkZ2F0dFN0bXSjY2FsZyZjc2lnWEcwRQIhALC8gX9KC3nSvEdQMMA2+v+3Iq9ka+Z5VjPd/lmFafYBAiAmqkZbOPqqPGoOTbGWtix5BCzCgSwnynUfyjKUontjBmN4NWOBWQLCMIICvjCCAaagAwIBAgIEVmYzfTANBgkqhkiG9w0BAQsFADAuMSwwKgYDVQQDEyNZdWJpY28gVTJGIFJvb3QgQ0EgU2VyaWFsIDQ1NzIwMDYzMTAgFw0xNDA4MDEwMDAwMDBaGA8yMDUwMDkwNDAwMDAwMFowbzELMAkGA1UEBhMCU0UxEjAQBgNVBAoMCVl1YmljbyBBQjEiMCAGA1UECwwZQXV0aGVudGljYXRvciBBdHRlc3RhdGlvbjEoMCYGA1UEAwwfWXViaWNvIFUyRiBFRSBTZXJpYWwgMTQ0OTUzODQyOTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABP+xrJlf6XDMMnA9bRko82Lah6fzgiAcabwNOmXVtrN1S/pIjFVuu+7SvZCS1wxucNVRAA8eKafgdT6x5RorEi2jbDBqMCIGCSsGAQQBgsQKAgQVMS4zLjYuMS40LjEuNDE0ODIuMS43MBMGCysGAQQBguUcAgEBBAQDAgUgMCEGCysGAQQBguUcAQEEBBIEEO6IKHlyHEkTl3U9/M6XByowDAYDVR0TAQH/BAIwADANBgkqhkiG9w0BAQsFAAOCAQEARBi3t4k06tSodFpONphG86pXtdGxs0TJMueuQxVed0HfqT7I2Y32RJQ2z6Vm4IhAR7FZSn0hYZ0cZQhvnq8PFbyNY6fM+t1WCMrXJ8SZCLH4aOMYgz0I85fkPpklabiYuNMP1w7wgLSoRowUfwsC4mWwNsFbchW4dxPn+f0H9bnjG+16V4m4mriF2xnI/Lurge5JCErbYwVfvULC8+nq5oFH8mFtpKGJAK8mOCJsuSLXqLKT5+6iGjEcJ1E86JJxEW1v2SKUN3r9AcWjE/QE+Uo5ldE8x52YXsDXuXFmOHtos8gN+QAGFLZ3x7x2N5n1H/iefiEAW5kVeZFeZTlD22hhdXRoRGF0YVjEFLv2y3mOmrYr9Bu00OCUlqkEVnBOAH4f4vCbym88jnNFAAAAAu6IKHlyHEkTl3U9/M6XByoAQHc+PLocUiTCDbYMIs7vb7z3+aNdzC6xkIcJNRA8bC0VAjiCmINN8ghcwLb4Sy4ayqJku8Kil8Il5d2W9z/1BHulAQIDJiABIVggyJEZv0JgeLEYlUIINM4Lzp28V7FhF6HCGajpdiLp1ckiWCBrPUa+fTa/N7QlIsyfiedV3KHfOzOEvN9h8+O5d0nGNg==\"}}"}`

**Comment by michib** [comment] 2020-05-02 11:14
@derritter88 Could you do me a favor and test on https://webauthn.spomky-labs.com/ if your stick works there?

**Comment by derritter88** [comment] 2020-05-02 11:26
Helli @michib 
didn't work as well - website showed me an "An error occurred during the registration process. Please try again later." error.

The console says: 
HTTP 401

`id: 8bRcDwItJ456H_a1pHolyjXIiYL1pkv7G0pfbq1DqxJ31hJVtftGR0noh3AlRamlajHW2ZSKafrmgbIbR1_WGtb4nypv5YDuBd8MXqprOn_57rckJ4OICUzonqNuhEGUfHuORkec1e8CJxIf5GSCeGYOfz9UMlNQCTWG_rEidRg`

`rawId: 8bRcDwItJ456H/a1pHolyjXIiYL1pkv7G0pfbq1DqxJ31hJVtftGR0noh3AlRamlajHW2ZSKafrmgbIbR1/WGtb4nypv5YDuBd8MXqprOn/57rckJ4OICUzonqNuhEGUfHuORkec1e8CJxIf5GSCeGYOfz9UMlNQCTWG/rEidRg=`

`attestationObject: o2NmbXRmcGFja2VkZ2F0dFN0bXSjY2FsZyZjc2lnWEcwRQIgaUp13PC22lerv6NxmmvyyfZM6AXiIqp9p2cs/D7a39UCIQC0+OUqYCHmROqGUUUP2mU+kobICpkwJRj+TYtCt6xT/2N4NWOBWQLCMIICvjCCAaagAwIBAgIEVmYzfTANBgkqhkiG9w0BAQsFADAuMSwwKgYDVQQDEyNZdWJpY28gVTJGIFJvb3QgQ0EgU2VyaWFsIDQ1NzIwMDYzMTAgFw0xNDA4MDEwMDAwMDBaGA8yMDUwMDkwNDAwMDAwMFowbzELMAkGA1UEBhMCU0UxEjAQBgNVBAoMCVl1YmljbyBBQjEiMCAGA1UECwwZQXV0aGVudGljYXRvciBBdHRlc3RhdGlvbjEoMCYGA1UEAwwfWXViaWNvIFUyRiBFRSBTZXJpYWwgMTQ0OTUzODQyOTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABP+xrJlf6XDMMnA9bRko82Lah6fzgiAcabwNOmXVtrN1S/pIjFVuu+7SvZCS1wxucNVRAA8eKafgdT6x5RorEi2jbDBqMCIGCSsGAQQBgsQKAgQVMS4zLjYuMS40LjEuNDE0ODIuMS43MBMGCysGAQQBguUcAgEBBAQDAgUgMCEGCysGAQQBguUcAQEEBBIEEO6IKHlyHEkTl3U9/M6XByowDAYDVR0TAQH/BAIwADANBgkqhkiG9w0BAQsFAAOCAQEARBi3t4k06tSodFpONphG86pXtdGxs0TJMueuQxVed0HfqT7I2Y32RJQ2z6Vm4IhAR7FZSn0hYZ0cZQhvnq8PFbyNY6fM+t1WCMrXJ8SZCLH4aOMYgz0I85fkPpklabiYuNMP1w7wgLSoRowUfwsC4mWwNsFbchW4dxPn+f0H9bnjG+16V4m4mriF2xnI/Lurge5JCErbYwVfvULC8+nq5oFH8mFtpKGJAK8mOCJsuSLXqLKT5+6iGjEcJ1E86JJxEW1v2SKUN3r9AcWjE/QE+Uo5ldE8x52YXsDXuXFmOHtos8gN+QAGFLZ3x7x2N5n1H/iefiEAW5kVeZFeZTlD22hhdXRoRGF0YVjhlgTqgoJOmKStoUtEYtDXOo7EaRMNqRsZMHRZIp90o1lFAAAAAu6IKHlyHEkTl3U9/M6XByoAgPG0XA8CLSeOeh/2taR6Jco1yImC9aZL+xtKX26tQ6sSd9YSVbX7RkdJ6IdwJUWppWox1tmUimn65oGyG0df1hrW+J8qb+WA7gXfDF6qazp/+e63JCeDiAlM6J6jboRBlHx7jkZHnNXvAicSH+RkgnhmDn8/VDJTUAk1hv6xInUYpAEBAycgBiFYIJfk4D/t5/F21J5sXrZ2cqLXUznuasRZpWwA9nOsIxiO`

`clientDataJSON: eyJjaGFsbGVuZ2UiOiJXdW1zZ195d0Jia0N4LWxiOUY5Zmk0dFo5Q3lfRDg1c0RiWWpCTVA1cllrIiwiY2xpZW50RXh0ZW5zaW9ucyI6e30sImhhc2hBbGdvcml0aG0iOiJTSEEtMjU2Iiwib3JpZ2luIjoiaHR0cHM6Ly93ZWJhdXRobi5zcG9ta3ktbGFicy5jb20iLCJ0eXBlIjoid2ViYXV0aG4uY3JlYXRlIn0=`

`type: public-key`


Hope this helps.

**Comment by michib** [comment] 2020-05-02 11:31
Oh thanks for the fast feedback. Yes this really helps. Unfortunately this means, i probably have to wait for https://github.com/web-auth/webauthn-framework/issues/123 to be resolved.

But if you have even more spare time, you could test on Linux with Firefox, or Win 10 with Chrome etc if it works. Probably yes, but would be really helpful feedback for me.

I will comment in this issue, as soon as i updated to the newer webauthn-lib after the issue fix has been released.

**Comment by michib** [comment] 2020-05-02 12:04
Spomky was fast :-D @derritter88 could you try it with this version: 
[twofactor_webauthn.tar.gz](https://github.com/michib/nextcloud_twofactor_webauthn/files/4567636/twofactor_webauthn.tar.gz)

**Comment by derritter88** [comment] 2020-05-02 12:14
Okay did it.
Removed the old twofactor_webauthn from Nextcloud/apps folder and placed yours.
Nextcloud asked me for an update which I did.

Result is still the same - it does not work.

**Comment by derritter88** [comment] 2020-05-02 13:29
`data: {"id":"Lox6KuStT8sWQ5wYPTKew_ixW9Dwy9YnLM8fBWoSez2OT0tYSC4nuFpxJI_WJAF9NaF_6APmafCPWRTzDC8nYg","type":"public-key","rawId":"Lox6KuStT8sWQ5wYPTKew/ixW9Dwy9YnLM8fBWoSez2OT0tYSC4nuFpxJI/WJAF9NaF/6APmafCPWRTzDC8nYg==","response":{"clientDataJSON":"eyJjaGFsbGVuZ2UiOiJVWnhKWVctN0FFZlRWRkVaakdPSkR4UDZFME9zdXRyNXp0OXZtLThGTnlVIiwiY2xpZW50RXh0ZW5zaW9ucyI6e30sImhhc2hBbGdvcml0aG0iOiJTSEEtMjU2Iiwib3JpZ2luIjoiaHR0cHM6Ly9jbG91ZC5oa3MtcHJvamVrdC5hdCIsInR5cGUiOiJ3ZWJhdXRobi5jcmVhdGUifQ==","attestationObject":"o2NmbXRmcGFja2VkZ2F0dFN0bXSjY2FsZyZjc2lnWEgwRgIhAPWJx35PJ2bohIYcrEsr6r3oiZXT489ZgwsVVB+e8nyvAiEA1FY3aEgpAFW5Ma79NzjaNInuPfAuXYkUOWnouo1sCSNjeDVjgVkCwjCCAr4wggGmoAMCAQICBFZmM30wDQYJKoZIhvcNAQELBQAwLjEsMCoGA1UEAxMjWXViaWNvIFUyRiBSb290IENBIFNlcmlhbCA0NTcyMDA2MzEwIBcNMTQwODAxMDAwMDAwWhgPMjA1MDA5MDQwMDAwMDBaMG8xCzAJBgNVBAYTAlNFMRIwEAYDVQQKDAlZdWJpY28gQUIxIjAgBgNVBAsMGUF1dGhlbnRpY2F0b3IgQXR0ZXN0YXRpb24xKDAmBgNVBAMMH1l1YmljbyBVMkYgRUUgU2VyaWFsIDE0NDk1Mzg0MjkwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAT/sayZX+lwzDJwPW0ZKPNi2oen84IgHGm8DTpl1bazdUv6SIxVbrvu0r2QktcMbnDVUQAPHimn4HU+seUaKxIto2wwajAiBgkrBgEEAYLECgIEFTEuMy42LjEuNC4xLjQxNDgyLjEuNzATBgsrBgEEAYLlHAIBAQQEAwIFIDAhBgsrBgEEAYLlHAEBBAQSBBDuiCh5chxJE5d1PfzOlwcqMAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggEBAEQYt7eJNOrUqHRaTjaYRvOqV7XRsbNEyTLnrkMVXndB36k+yNmN9kSUNs+lZuCIQEexWUp9IWGdHGUIb56vDxW8jWOnzPrdVgjK1yfEmQix+GjjGIM9CPOX5D6ZJWm4mLjTD9cO8IC0qEaMFH8LAuJlsDbBW3IVuHcT5/n9B/W54xvteleJuJq4hdsZyPy7q4HuSQhK22MFX71CwvPp6uaBR/JhbaShiQCvJjgibLki16iyk+fuohoxHCdRPOiScRFtb9kilDd6/QHFoxP0BPlKOZXRPMedmF7A17lxZjh7aLPIDfkABhS2d8e8djeZ9R/4nn4hAFuZFXmRXmU5Q9toYXV0aERhdGFYxBS79st5jpq2K/QbtNDglJapBFZwTgB+H+Lwm8pvPI5zRQAAAAPuiCh5chxJE5d1PfzOlwcqAEAujHoq5K1PyxZDnBg9Mp7D+LFb0PDL1icszx8FahJ7PY5PS1hILie4WnEkj9YkAX01oX/oA+Zp8I9ZFPMMLydipQECAyYgASFYIN6wh387jwt6qpE+AopK7iGGx2vzbs58lHmWuQ7gn64hIlgg0/8WCKBk97kFAlPi2X5fxO8A/DgGTKXRAOVnW1+dGBM="}}`

**Comment by derritter88** [comment] 2020-05-02 13:30
Nextcloud log says:
`

Error | index | Assert\InvalidArgumentException: The attestation statement has no key "alg"./var/www/cloud/apps/twofactor_webauthn/vendor/beberlei/assert/lib/Assert/Assertion.php - line 1769: Assert\Assertion::createException(false, "The attesta ... .", 32, null)/var/www/cloud/apps/twofactor_webauthn/vendor/web-auth/webauthn-lib/src/AttestationStatement/AttestationStatement.php - line 123: Assert\Assertion::true(false, "The attesta ... .")/var/www/cloud/apps/twofactor_webauthn/vendor/web-auth/webauthn-lib/src/AttestationStatement/PackedAttestationStatementSupport.php - line 180: Webauthn\AttestationStatement\AttestationStatement->get("alg")/var/www/cloud/apps/twofactor_webauthn/vendor/web-auth/webauthn-lib/src/AttestationStatement/PackedAttestationStatementSupport.php - line 85: Webauthn\AttestationStatement\PackedAttestationStatementSupport->processWithSelfAttestation(null, Webauthn\Att ... {}, Webauthn\AuthenticatorData {})/var/www/cloud/apps/twofactor_webauthn/vendor/web-auth/webauthn-lib/src/AuthenticatorAttestationResponseValidator.php - line 157: Webauthn\AttestationStatement\PackedAttestationStatementSupport->isValid(null, Webauthn\Att ... {}, Webauthn\AuthenticatorData {})/var/www/cloud/apps/twofactor_webauthn/lib/Service/WebauthnManager.php - line 245: Webauthn\AuthenticatorAttestationResponseValidator->check(Webauthn\Aut ... {}, Webauthn\Pub ... {}, Slim\Http\Request {})/var/www/cloud/apps/twofactor_webauthn/lib/Controller/SettingsController.php - line 87: OCA\TwoFactorWebauthn\Service\WebauthnManager->finishRegister(OC\User\User {}, "Yubikey 5C", "{\"id\":\"L ... }")/var/www/cloud/lib/private/AppFramework/Http/Dispatcher.php - line 170: OCA\TwoFactorWebauthn\Controller\SettingsController->finishRegister("Yubikey 5C", "{\"id\":\"L ... }")/var/www/cloud/lib/private/AppFramework/Http/Dispatcher.php - line 99: OC\AppFramework\Http\Dispatcher->executeController(OCA\TwoFacto ... {}, "finishRegister")/var/www/cloud/lib/private/AppFramework/App.php - line 125: OC\AppFramework\Http\Dispatcher->dispatch(OCA\TwoFacto ... {}, "finishRegister")/var/www/cloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("OCA\\TwoFac ... r", "finishRegister", OC\AppFramew ... {}, { _route: "t ... "})<<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "t ... "})/var/www/cloud/lib/private/Route/Router.php - line 299: call_user_func(OC\AppFramew ... {}, { _route: "t ... "})/var/www/cloud/lib/base.php - line 1008: OC\Route\Router->match("/apps/twofa ... r")/var/www/cloud/index.php - line 38: OC::handleRequest()
-- | -- | --


`

**Comment by derritter88** [comment] 2020-05-02 17:52
A useful information:
I tried to register my Yubikey via my Ubuntu 20.04 notebook (Firefox) - it worked without any issues.
Could this be a problem from the Windows 10 side as Windows uses a dedicated mode for handling U2F/FIDO2 requests.
E.g. on Windows I have to enter a PIN to use FIDO2 - on Ubuntu not.

**Comment by derritter88** [comment] 2020-05-02 17:56
Okay, after registration of my Yubikey via Ubuntu the login on Windows 10 works without any issues/errors.
Also within Nextcloud log there is no sign of an issue.

**Comment by michib** [comment] 2020-05-03 07:44
Could you just for testing purposes try to register with chrome under win 10? As described in the bug from the webauthn-lib this just happens with edge and firefox, so it would be great if you could confirm this.
I'm going to investigate the new error message

**Comment by derritter88** [comment] 2020-05-03 17:52
I have tested now with current Google chrome - worked also without any issues.

In addition I also tried again with Firefox with deactivated addons - did not work as well.


So the problem lies somewhere within Firefox on Win10.

**Comment by michib** [comment] 2020-05-03 18:03
I have the problem that i can't reproduce the issue with my hardware. I tried it myself on win 10 with firefox 75 but it appears because my yubikey 5 nfc is of the first generation (which doesn't support all webauthn features), it does not create a packed attestation, which your yubikey does. So either someone is willing to buy me a new yubikey (which i would surely appreciate :smirk:) or i have to implement a fake authenticator which i need for tests nevertheless. 
But the latter isn't done correctly in a few minutes, so i'm afraid you have to live the workaround as to register your keys with chrome till i have time to create the fake authenticators and debug the issue.

**Comment by derritter88** [comment] 2020-05-03 18:06
I moved from Yubikey 4 & NEO to 5C to have FIDO2 and also USB-C as my laptop does not have any USB-A ports.

Currently I am using the Twofactor U2F which is also fine for me.

If you need anyone who tests your development - feel free to stick with me :-)

**Comment by michib** [comment] 2020-05-03 18:20
The Yubikey 4 also works with FIDO2 as webauthn. I'm testing with both sticks, the yubikey 4 neo and the yubikey 5 nfc.

Every Tester is highly welcome and appreciated :grinning:, so thank you very much for your offer. I'm surely going to ask you for tests as soon as this extension reaches a somewhat stable level. And without people like you who are willing to test it in this early stage, it won't reach a stable level. So thank you again, your tests are really helpful.

**Comment by derritter88** [comment] 2020-05-03 18:22
Yeah I know that - I am not well at coding (although I can read sources) but I am happy to act as alpha/beta tester and log my issues at Github or something else :-)

**Comment by isdnfan** [comment] 2021-05-28 09:50
I have the same issue as I can't use my Nitrokey FIDO2 on NC21.0.2 with Two-Factor Webauthn 0.2.9 - feel free to ask me for testing (both fails registering new device and using a device registered in previous versions - details: https://help.nextcloud.com/t/log-in-by-device-yubikey-fails/116249/17 )

**Comment by isdnfan** [comment] 2021-06-08 07:27
Just tested successfully using latest docker NC 21.0.2 (version from 04.06.2021) and Two-Factor Webauthn 0.2.10

**Comment by derritter88** [comment] 2021-06-09 08:37
I still have some issues: 

[ERROR] settings: Error persisting webauthn registration 
Object { app: "settings", uid: "3A60C52D-9415-4F28-A2B7-71A8CBD7A9E3", error: Error }
​
app: "settings"
​
error: Error: Request failed with status code 500
​
uid: "3A60C52D-9415-4F28-A2B7-71A8CBD7A9E3"
​
<prototype>: Object { … }
ConsoleLogger.js:54:18
    value ConsoleLogger.js:54
    value ConsoleLogger.js:80
    e AddDevice.vue:190
    l runtime.js:63
    _invoke runtime.js:293
    v runtime.js:118
    w vue-settings-personal-webauthn.js:1
    a vue-settings-personal-webauthn.js:1
    (Async: promise callback)
    w vue-settings-personal-webauthn.js:1
    i vue-settings-personal-webauthn.js:1
    saveRegistrationData vue-settings-personal-webauthn.js:1
    saveRegistrationData vue-settings-personal-webauthn.js:1
    saveRegistrationData vue-settings-personal-webauthn.js:1
    submit AddDevice.vue:175
    VueJS 28
    start AddDevice.vue:112
    (Async: promise callback)
    start AddDevice.vue:112
    VueJS 2

**Comment by michib** [comment] 2021-08-02 18:07
Hi, sorry for the late reply, somehow i didn't get any notification mails and just happened to check the issues. 
Are you sure this is related to the second factor authentication or are you trying to setup the first factor auth? There is no AddDevice.vue nor vue-settings-personal-webauthn.js file in this project.

**Closed** 2021-10-06 10:52 UTC
Labels: bug
